### PR TITLE
add control_custom_channels

### PR DESCRIPTION
**Pull request by Pfleiderer-Adrian**
- add control_custom_channel-function line: 319
- add set_custom_channel-function line: 328

### CODE REVIEW

**Comment by Pfleiderer-Adrian** [comment]
Issue: https://github.com/SomethingWithComputers/pixoo/issues/8

**Review by SomethingWithComputers — CHANGES_REQUESTED** [review]
Hey there! Good catch!
You might've noticed that all methods are in alphabetical order. Do you think you can refactor it to fit more with the current source code? Also I think that it should be named `def set_custom_page(self, index)` to more accurately reflect its functionality.

If you don't have the time, I can implement this with the next update :)!

**Comment by Pfleiderer-Adrian** [comment]
Hi,
refactored functions are pushed. :)

**Review by SomethingWithComputers — APPROVED** [review]
Nice!

**Pull request merged**
